# name: Start EC2 Runner
# on:
#   workflow_dispatch:
#   schedule:
#     - cron: '*/5 * * * *' # Check every 5 minutes

# jobs:
#   start-runner:
#     runs-on: self-hosted
#     steps:
#       - name: Check for queued jobs
#         id: check-queued-jobs
#         uses: actions/github-script@v6
#         with:
#           script: |
#             const { data: jobs } = await github.rest.actions.listJobsForWorkflowRun({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               run_id: context.runId,
#             });
#             const queuedJobs = jobs.jobs.filter(job => job.status === 'queued');
#             return queuedJobs.length > 0;

#       - name: Start EC2 Instance
#         if: steps.check-queued-jobs.outputs.result == 'true'
#         with:
#           region: 'us-west-1' # Replace with your region
#           instance-id: 'ami-07d2649d67dbe8900' # Replace with your EC2 instance ID
#           action: 'start'
