

name: check instance id
on:
  push:
    branches:
      - main
jobs:
  identify-runner:
    runs-on: [ec2-i-02d2977c0b4cb7244]
    steps:
      - name: Get EC2 Instance ID
        run: |
          INSTANCE_ID=$(ec2metadata --instance-id)
          echo "Running job on EC2 Instance: $INSTANCE_ID"
