
name: check instance id
on:
  push:
    branches:
      - main
jobs:
  identify-runner:
    runs-on: [self-hosted, ec2-i-09075dc0f5618a58c]
    steps:
      - name: Get EC2 Instance ID
        run: |
          INSTANCE_ID=$(ec2metadata --instance-id)
          echo "Running job on EC2 Instance: $INSTANCE_ID"
