name: EC2 Self-hosted Runner 

on:
  # Trigger when a new job is queued or when a push is made
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Schedule job to check for idle EC2 instance every 15 minutes
  schedule:
    - cron: '*/15 * * * *'  # Check every 15 minutes

jobs:
  # This job ensures the EC2 instance is running if there is a job queued
  manage-ec2-start:
    runs-on: ubuntu-latest # GitHub-hosted runner to start the EC2 if it's not running

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start EC2 Instance if Stopped
        run: |
          INSTANCE_ID="i-0bcdce5e423c87bea"
          # Use AWS CLI to check the EC2 instance status
          STATUS=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].State.Name" --output text)

          # Start the EC2 instance if it's stopped
          if [[ "$STATUS" == "stopped" ]]; then
            echo "Starting EC2 instance..."
            aws ec2 start-instances --instance-ids $INSTANCE_ID
          else
            echo "EC2 instance is already running."
          fi

  # This job will check if there are active jobs or workflows
  # If no jobs are active, EC2 instance will be stopped after 15 minutes
  manage-ec2-stop:
    runs-on: ubuntu-latest  # GitHub-hosted runner to check the EC2 instance status

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for active jobs
        run: |
          RUNNING_JOBS=$(curl -s -H "Authorization: token ${{ secrets.REPO_TOKEN }}" "https://api.github.com/repos/aqeelsadiq/test/actions/runs" | jq '.workflow_runs | length')

          if [ "$RUNNING_JOBS" -eq 0 ]; then
            INSTANCE_ID="i-0bcdce5e423c87bea"
            echo "No active jobs. Stopping EC2 instance after 15 minutes of inactivity..."
            aws ec2 stop-instances --instance-ids $INSTANCE_ID
          else
            echo "There are active jobs. EC2 instance remains running."
          fi

  # Your workflow job that runs on the self-hosted runner
  build:
    runs-on: self-hosted  # EC2 instance should act as the self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          echo "Building and running tests on EC2..."
